// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulanceControlService.proto

package grpc.ambulanceControlService;

public interface AmbulanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AmbulanceControlService.AmbulanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ph no.
   * </pre>
   *
   * <code>int32 numbers = 1;</code>
   */
  int getNumbers();

  /**
   * <pre>
   *name
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *name
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *address
   * </pre>
   *
   * <code>string address = 3;</code>
   */
  java.lang.String getAddress();
  /**
   * <pre>
   *address
   * </pre>
   *
   * <code>string address = 3;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
