// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulanceControlService.proto

package grpc.ambulanceControlService;

public interface AmbulanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AmbulanceControlService.AmbulanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ambulance send
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   *ambulance send
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
