// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulanceControlService.proto

package grpc.ambulanceControlService;

/**
 * Protobuf type {@code AmbulanceControlService.sendRequest}
 */
public  final class sendRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:AmbulanceControlService.sendRequest)
    sendRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use sendRequest.newBuilder() to construct.
  private sendRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private sendRequest() {
    ambulancenumber_ = 0;
    fromBase_ = "";
    toBase_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private sendRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            ambulancenumber_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            fromBase_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            toBase_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.ambulanceControlService.ambulanceControlServiceImpl.internal_static_AmbulanceControlService_sendRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.ambulanceControlService.ambulanceControlServiceImpl.internal_static_AmbulanceControlService_sendRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ambulanceControlService.sendRequest.class, grpc.ambulanceControlService.sendRequest.Builder.class);
  }

  public static final int AMBULANCENUMBER_FIELD_NUMBER = 1;
  private int ambulancenumber_;
  /**
   * <pre>
   *ambulance no.
   * </pre>
   *
   * <code>int32 ambulancenumber = 1;</code>
   */
  public int getAmbulancenumber() {
    return ambulancenumber_;
  }

  public static final int FROMBASE_FIELD_NUMBER = 2;
  private volatile java.lang.Object fromBase_;
  /**
   * <pre>
   *accident,injury
   * </pre>
   *
   * <code>string fromBase = 2;</code>
   */
  public java.lang.String getFromBase() {
    java.lang.Object ref = fromBase_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromBase_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *accident,injury
   * </pre>
   *
   * <code>string fromBase = 2;</code>
   */
  public com.google.protobuf.ByteString
      getFromBaseBytes() {
    java.lang.Object ref = fromBase_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromBase_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOBASE_FIELD_NUMBER = 3;
  private volatile java.lang.Object toBase_;
  /**
   * <pre>
   *sick, health issues
   * </pre>
   *
   * <code>string toBase = 3;</code>
   */
  public java.lang.String getToBase() {
    java.lang.Object ref = toBase_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toBase_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *sick, health issues
   * </pre>
   *
   * <code>string toBase = 3;</code>
   */
  public com.google.protobuf.ByteString
      getToBaseBytes() {
    java.lang.Object ref = toBase_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toBase_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ambulancenumber_ != 0) {
      output.writeInt32(1, ambulancenumber_);
    }
    if (!getFromBaseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fromBase_);
    }
    if (!getToBaseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, toBase_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ambulancenumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, ambulancenumber_);
    }
    if (!getFromBaseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fromBase_);
    }
    if (!getToBaseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, toBase_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ambulanceControlService.sendRequest)) {
      return super.equals(obj);
    }
    grpc.ambulanceControlService.sendRequest other = (grpc.ambulanceControlService.sendRequest) obj;

    boolean result = true;
    result = result && (getAmbulancenumber()
        == other.getAmbulancenumber());
    result = result && getFromBase()
        .equals(other.getFromBase());
    result = result && getToBase()
        .equals(other.getToBase());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AMBULANCENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getAmbulancenumber();
    hash = (37 * hash) + FROMBASE_FIELD_NUMBER;
    hash = (53 * hash) + getFromBase().hashCode();
    hash = (37 * hash) + TOBASE_FIELD_NUMBER;
    hash = (53 * hash) + getToBase().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ambulanceControlService.sendRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ambulanceControlService.sendRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.ambulanceControlService.sendRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ambulanceControlService.sendRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ambulanceControlService.sendRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code AmbulanceControlService.sendRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:AmbulanceControlService.sendRequest)
      grpc.ambulanceControlService.sendRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ambulanceControlService.ambulanceControlServiceImpl.internal_static_AmbulanceControlService_sendRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ambulanceControlService.ambulanceControlServiceImpl.internal_static_AmbulanceControlService_sendRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ambulanceControlService.sendRequest.class, grpc.ambulanceControlService.sendRequest.Builder.class);
    }

    // Construct using grpc.ambulanceControlService.sendRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ambulancenumber_ = 0;

      fromBase_ = "";

      toBase_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.ambulanceControlService.ambulanceControlServiceImpl.internal_static_AmbulanceControlService_sendRequest_descriptor;
    }

    @java.lang.Override
    public grpc.ambulanceControlService.sendRequest getDefaultInstanceForType() {
      return grpc.ambulanceControlService.sendRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ambulanceControlService.sendRequest build() {
      grpc.ambulanceControlService.sendRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ambulanceControlService.sendRequest buildPartial() {
      grpc.ambulanceControlService.sendRequest result = new grpc.ambulanceControlService.sendRequest(this);
      result.ambulancenumber_ = ambulancenumber_;
      result.fromBase_ = fromBase_;
      result.toBase_ = toBase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ambulanceControlService.sendRequest) {
        return mergeFrom((grpc.ambulanceControlService.sendRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ambulanceControlService.sendRequest other) {
      if (other == grpc.ambulanceControlService.sendRequest.getDefaultInstance()) return this;
      if (other.getAmbulancenumber() != 0) {
        setAmbulancenumber(other.getAmbulancenumber());
      }
      if (!other.getFromBase().isEmpty()) {
        fromBase_ = other.fromBase_;
        onChanged();
      }
      if (!other.getToBase().isEmpty()) {
        toBase_ = other.toBase_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.ambulanceControlService.sendRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.ambulanceControlService.sendRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ambulancenumber_ ;
    /**
     * <pre>
     *ambulance no.
     * </pre>
     *
     * <code>int32 ambulancenumber = 1;</code>
     */
    public int getAmbulancenumber() {
      return ambulancenumber_;
    }
    /**
     * <pre>
     *ambulance no.
     * </pre>
     *
     * <code>int32 ambulancenumber = 1;</code>
     */
    public Builder setAmbulancenumber(int value) {
      
      ambulancenumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ambulance no.
     * </pre>
     *
     * <code>int32 ambulancenumber = 1;</code>
     */
    public Builder clearAmbulancenumber() {
      
      ambulancenumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object fromBase_ = "";
    /**
     * <pre>
     *accident,injury
     * </pre>
     *
     * <code>string fromBase = 2;</code>
     */
    public java.lang.String getFromBase() {
      java.lang.Object ref = fromBase_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromBase_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *accident,injury
     * </pre>
     *
     * <code>string fromBase = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFromBaseBytes() {
      java.lang.Object ref = fromBase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromBase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *accident,injury
     * </pre>
     *
     * <code>string fromBase = 2;</code>
     */
    public Builder setFromBase(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromBase_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *accident,injury
     * </pre>
     *
     * <code>string fromBase = 2;</code>
     */
    public Builder clearFromBase() {
      
      fromBase_ = getDefaultInstance().getFromBase();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *accident,injury
     * </pre>
     *
     * <code>string fromBase = 2;</code>
     */
    public Builder setFromBaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromBase_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toBase_ = "";
    /**
     * <pre>
     *sick, health issues
     * </pre>
     *
     * <code>string toBase = 3;</code>
     */
    public java.lang.String getToBase() {
      java.lang.Object ref = toBase_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toBase_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *sick, health issues
     * </pre>
     *
     * <code>string toBase = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToBaseBytes() {
      java.lang.Object ref = toBase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toBase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *sick, health issues
     * </pre>
     *
     * <code>string toBase = 3;</code>
     */
    public Builder setToBase(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toBase_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *sick, health issues
     * </pre>
     *
     * <code>string toBase = 3;</code>
     */
    public Builder clearToBase() {
      
      toBase_ = getDefaultInstance().getToBase();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *sick, health issues
     * </pre>
     *
     * <code>string toBase = 3;</code>
     */
    public Builder setToBaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toBase_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:AmbulanceControlService.sendRequest)
  }

  // @@protoc_insertion_point(class_scope:AmbulanceControlService.sendRequest)
  private static final grpc.ambulanceControlService.sendRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ambulanceControlService.sendRequest();
  }

  public static grpc.ambulanceControlService.sendRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<sendRequest>
      PARSER = new com.google.protobuf.AbstractParser<sendRequest>() {
    @java.lang.Override
    public sendRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new sendRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<sendRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<sendRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ambulanceControlService.sendRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

