// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ambulanceControlService.proto

package grpc.ambulanceControlService;

public interface sendRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AmbulanceControlService.sendRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ambulance no.
   * </pre>
   *
   * <code>int32 ambulancenumber = 1;</code>
   */
  int getAmbulancenumber();

  /**
   * <pre>
   *accident,injury
   * </pre>
   *
   * <code>string fromBase = 2;</code>
   */
  java.lang.String getFromBase();
  /**
   * <pre>
   *accident,injury
   * </pre>
   *
   * <code>string fromBase = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBaseBytes();

  /**
   * <pre>
   *sick, health issues
   * </pre>
   *
   * <code>string toBase = 3;</code>
   */
  java.lang.String getToBase();
  /**
   * <pre>
   *sick, health issues
   * </pre>
   *
   * <code>string toBase = 3;</code>
   */
  com.google.protobuf.ByteString
      getToBaseBytes();
}
