// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registrationControlService.proto

package grpc.registrationControlService;

public interface HospitalHelpRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationControlService.HospitalHelpRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hospitalHelp = 1;</code>
   */
  java.lang.String getHospitalHelp();
  /**
   * <code>string hospitalHelp = 1;</code>
   */
  com.google.protobuf.ByteString
      getHospitalHelpBytes();
}
