// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registrationControlService.proto

package grpc.registrationControlService;

public final class registrationControlServiceImpl {
  private registrationControlServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationControlService_HospitalHelpRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationControlService_HospitalHelpRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationControlService_HospitalHelpResponce_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationControlService_HospitalHelpResponce_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationControlService_sendRegistrationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationControlService_sendRegistrationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationControlService_sendResgistrationResponce_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationControlService_sendResgistrationResponce_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n registrationControlService.proto\022\032Regi" +
      "strationControlService\"+\n\023HospitalHelpRe" +
      "quest\022\024\n\014hospitalHelp\030\001 \001(\t\",\n\024HospitalH" +
      "elpResponce\022\024\n\014hospitalHelp\030\001 \001(\t\".\n\027sen" +
      "dRegistrationRequest\022\023\n\013firstString\030\001 \001(" +
      "\t\"0\n\031sendResgistrationResponce\022\023\n\013firstS" +
      "tring\030\001 \001(\t2\242\002\n\032registrationControlServi" +
      "ce\022v\n\017GetHospitalHelp\022/.RegistrationCont" +
      "rolService.HospitalHelpRequest\0320.Registr" +
      "ationControlService.HospitalHelpResponce" +
      "\"\000\022\213\001\n\031SendStringClientStreaming\0223.Regis" +
      "trationControlService.sendRegistrationRe" +
      "quest\0325.RegistrationControlService.sendR" +
      "esgistrationResponce\"\000(\001BC\n\037grpc.registr" +
      "ationControlServiceB\036registrationControl" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RegistrationControlService_HospitalHelpRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RegistrationControlService_HospitalHelpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationControlService_HospitalHelpRequest_descriptor,
        new java.lang.String[] { "HospitalHelp", });
    internal_static_RegistrationControlService_HospitalHelpResponce_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RegistrationControlService_HospitalHelpResponce_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationControlService_HospitalHelpResponce_descriptor,
        new java.lang.String[] { "HospitalHelp", });
    internal_static_RegistrationControlService_sendRegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RegistrationControlService_sendRegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationControlService_sendRegistrationRequest_descriptor,
        new java.lang.String[] { "FirstString", });
    internal_static_RegistrationControlService_sendResgistrationResponce_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RegistrationControlService_sendResgistrationResponce_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationControlService_sendResgistrationResponce_descriptor,
        new java.lang.String[] { "FirstString", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
