// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registrationControlService.proto

package grpc.registrationControlService;

public interface sendRegistrationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationControlService.sendRegistrationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstString = 1;</code>
   */
  java.lang.String getFirstString();
  /**
   * <code>string firstString = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
